[package]
name = "rust-ml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candle-core = "0.2.2"
candle-datasets = "0.2.2"
candle-nn = "0.2.2"
clap = "4.4.5"
rand = "0.8.5"
thiserror = "1.0.48"
